# .github/workflows/docker-image-build.yaml
name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - master



permissions: write-all
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .



          push: true

          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quakewatch:v0.${{ github.run_number }}

      - name: Checkout Ops repository
        uses: actions/checkout@v3
        with:

          repository: ronaelshef3/GITops

          path: ops-repo



          token: ${{ secrets.GIT-OPS}}
          ssh-strict: true
          persist-credentials: true




      - name: Update values.yaml in Ops repo (using yq)
        run: |

          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

          NEW_TAG="v0.${{ github.run_number }}"
          # <--- נניח שזה הנתיב לקובץ הראשי בריפו ה-Ops
          VALUES_FILE_PATH="ops-repo/my-app-chart/values.yaml"

          # נעדכן את השדה image.tag בתוך הקובץ
          yq -i ".image.tag = \"$NEW_TAG\"" $VALUES_FILE_PATH

      - name: Commit updated values.yaml to Ops repo
        run: |
          # ניכנס לתיקיית ריפו ה-Ops ששכפלנו
          cd ops-repo


          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"


          # הנתיב כאן הוא יחסי ל-ops-repo
          git add my-app-chart/values.yaml


          if git diff-index --quiet HEAD; then
            echo "No changes to commit to Ops repo."
          else

            git commit -m "Update image tag for quakewatch to v0.${{ github.run_number }} [skip ci]"

            # נדחוף את השינוי לריפו ה-Ops
            git push
          fi