# .github/workflows/docker-image-build.yaml
name: Build and Deploy Docker Image

on:
  push:
    branches:
      - "*"



permissions: write-all
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: test
        run: python3 -m pytest tests/test.py

